// flow-typed signature: 4a7a58ff47cd332421a15dd0cbb5027f
// flow-typed version: <<STUB>>/react-throttle_v^0.3.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-throttle/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-throttle/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/classes/processors/Base' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/classes/processors/Debouncer' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/classes/processors/helpers/debounce' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/classes/processors/helpers/throttle' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/classes/processors/Throttler' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/components/Base' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/components/Debounce' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/components/Throttle' {
  declare module.exports: any;
}

declare module 'react-throttle/lib/index' {
  declare module.exports: any;
}

declare module 'react-throttle/test/helpers/isWrappedFunction' {
  declare module.exports: any;
}

declare module 'react-throttle/test/unit/components/debouncer' {
  declare module.exports: any;
}

declare module 'react-throttle/test/unit/processors/base' {
  declare module.exports: any;
}

declare module 'react-throttle/test/unit/processors/debouncer' {
  declare module.exports: any;
}

declare module 'react-throttle/test/unit/processors/throttler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-throttle/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-throttle/coverage/lcov-report/prettify'>;
}
declare module 'react-throttle/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-throttle/coverage/lcov-report/sorter'>;
}
declare module 'react-throttle/lib/classes/processors/Base.js' {
  declare module.exports: $Exports<'react-throttle/lib/classes/processors/Base'>;
}
declare module 'react-throttle/lib/classes/processors/Debouncer.js' {
  declare module.exports: $Exports<'react-throttle/lib/classes/processors/Debouncer'>;
}
declare module 'react-throttle/lib/classes/processors/helpers/debounce.js' {
  declare module.exports: $Exports<'react-throttle/lib/classes/processors/helpers/debounce'>;
}
declare module 'react-throttle/lib/classes/processors/helpers/throttle.js' {
  declare module.exports: $Exports<'react-throttle/lib/classes/processors/helpers/throttle'>;
}
declare module 'react-throttle/lib/classes/processors/Throttler.js' {
  declare module.exports: $Exports<'react-throttle/lib/classes/processors/Throttler'>;
}
declare module 'react-throttle/lib/components/Base.js' {
  declare module.exports: $Exports<'react-throttle/lib/components/Base'>;
}
declare module 'react-throttle/lib/components/Debounce.js' {
  declare module.exports: $Exports<'react-throttle/lib/components/Debounce'>;
}
declare module 'react-throttle/lib/components/Throttle.js' {
  declare module.exports: $Exports<'react-throttle/lib/components/Throttle'>;
}
declare module 'react-throttle/lib/index.js' {
  declare module.exports: $Exports<'react-throttle/lib/index'>;
}
declare module 'react-throttle/test/helpers/isWrappedFunction.js' {
  declare module.exports: $Exports<'react-throttle/test/helpers/isWrappedFunction'>;
}
declare module 'react-throttle/test/unit/components/debouncer.js' {
  declare module.exports: $Exports<'react-throttle/test/unit/components/debouncer'>;
}
declare module 'react-throttle/test/unit/processors/base.js' {
  declare module.exports: $Exports<'react-throttle/test/unit/processors/base'>;
}
declare module 'react-throttle/test/unit/processors/debouncer.js' {
  declare module.exports: $Exports<'react-throttle/test/unit/processors/debouncer'>;
}
declare module 'react-throttle/test/unit/processors/throttler.js' {
  declare module.exports: $Exports<'react-throttle/test/unit/processors/throttler'>;
}
